### ISSUE TITLE
git lfs: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by triffid** [pia-foss/desktop#46]
```
$ git lfs install
$ git clone https://github.com/pia-foss/desktop.git pia-desktop
Cloning into 'pia-desktop'...
remote: Enumerating objects: 10395, done.
remote: Counting objects: 100% (3676/3676), done.
remote: Compressing objects: 100% (2225/2225), done.
remote: Total 10395 (delta 1807), reused 2810 (delta 1371), pack-reused 6719
Receiving objects: 100% (10395/10395), 56.48 MiB | 15.41 MiB/s, done.
Resolving deltas: 100% (5248/5248), done.
Downloading brands/pia/gen_res/img/tray/sample-auto.png (1.6 KB)
Error downloading object: brands/pia/gen_res/img/tray/sample-auto.png (a70d879): Smudge error: Error downloading brands/pia/gen_res/img/tray/sample-auto.png (a70d879b122d80c3db6e66084670cb5afde09842972af27e740fb59894549979): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/home/triffid/Projects/pia-desktop/.git/lfs/logs/20221010T213233.230265197.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: brands/pia/gen_res/img/tray/sample-auto.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

```
pia-desktop $ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/pia-foss/desktop.git/info/lfs'
```

```
$ QTROOT=/usr/include/qt5/QtCore/5.15.5 rake --trace
Found Qt: /usr/include/qt5/QtCore/5.15.5
note: Different patch number from preferred version 5.15.2
Host: x86_64 -
Target: x86_64 -
Detected clang 14 at /usr/lib/llvm/14/bin (/usr/lib/llvm/14/bin/clang, /usr/lib/llvm/14/bin/clang++)
rake aborted!
Repository was not cloned with LFS.  Set up Git LFS and update; see README.md
/home/triffid/Projects/pia-desktop/Rakefile:19:in `<top (required)>'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:103:in `load_rakefile'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:82:in `block in run'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/usr/lib64/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/bin/rake:9:in `load'
/usr/bin/rake:9:in `<main>'
```

**Comment by justinxiao8** [comment]
has this been ongoing since 2022?

**Comment by triffid** [comment]
Don't know, maybe?

I ran into this then [made my own client](https://github.com/triffid/pia-wg) and haven't checked back

**Comment by kp-john-mair** [comment]
This should be fixed now! Thanks
